# Generated by Django 5.1.2 on 2024-10-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_author_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authrol',
            options={'verbose_name': 'Rol'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='authrol',
            table=None,
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
