# Generated by Django 5.1.2 on 2024-10-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_authrol_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario'},
        ),
    ]
